/* eslint-disable no-unused-vars */
/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "signifylights adapter settings": {
        "en": "Adapter settings for signifylights",
        "de": "Adaptereinstellungen für Signifylights",
        "ru": "Параметры адаптера для Signifylights",
        "pt": "Configurações do adaptador para significar luzes",
        "nl": "Adapter setting voor gebaren",
        "fr": "Paramètres d'adaptateur pour les feux de signalisation",
        "it": "Impostazioni adattatori per segnalibri",
        "es": "Ajustes del adaptador para los focos de señalización",
        "pl": "Adaptery oznaczają światło",
        "uk": "Параметри адаптера для вивісок",
        "zh-cn": "标志的标志环境"
    },
    "active": {
        "en": "Active",
        "de": "Aktiv",
        "ru": "Активно",
        "pt": "Activo",
        "nl": "Active",
        "fr": "Active",
        "it": "Attivo",
        "es": "Activo",
        "pl": "Aktywny",
        "uk": "Активний",
        "zh-cn": "精算师"
    },
    "addresses":   {
        "en": "addresses to monitoring",
        "de": "Adressen zur Überwachung"
    },
    "interval":    {
        "en": "Polling interval[sec]",
        "de": "Abfrageintervall [Sek.]"
    },
    "ipaddress":   {
        "en": "IP Address",
        "de": "IP Adresse"
    },
    "name":        {
        "en": "Name",
        "de": "Name"
    },
    "settings":    {
        "en": "Adapter settings",
        "de": "Adaptereinstellungen"
    },
    "bind_ip": {
        "en": "Bind IP-Adress",
        "de": "Lauschende IP-Adresse"
    },
    "register_devices": {
        "en": "register devices for auto update",
        "de": "Registrieren Sie Geräte für die automatische Aktualisierung"
    },
    "polling_intervall": {
        "en": "polling intervall (sec)",
        "de": "Polling-Intervall (Sek.)"
    },
    "listed_online": {
        "en": "treat as online (sec)",
        "de": "als online behandeln (Sek.)"
    },
};
