/* eslint-disable no-unused-vars */
/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "signifylights adapter settings": {
        "en": "Adapter settings for signifylights"
    },
    "active": {
        "en": "Active"
    },
    "addresses":   {
        "en": "addresses to monitoring"
    },
    "interval":    {
        "en": "Polling interval[sec]"
    },
    "ipaddress":   {
        "en": "IP Address"
    },
    "name":        {
        "en": "Name"
    },
    "settings":    {
        "en": "Adapter settings"
    },
    "bind_ip": {
        "en": "Bind IP-Adress"
    },
    "register_devices": {
        "en": "register devices for auto update"
    },
    "polling_intervall": {
        "en": "polling intervall (sec)"
    },
    "listed_online": {
        "en": "treat as online (sec)"
    },
};
